# Generated by Django 4.0.6 on 2022-10-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('evnet_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=70)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=70)),
                ('image', models.ImageField(default='', upload_to='shop/image')),
            ],
        ),
    ]
