# Generated by Django 4.0.6 on 2022-10-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
