# Generated by Django 4.0.6 on 2022-10-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_eventdetail_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='image',
            field=models.ImageField(default='', upload_to='tech/image'),
        ),
    ]
